# ref. https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: es01
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
